#!/usr/bin/env node

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const compatibilityPath = resolve(root, "compatibility/liveview.json");
const capabilitiesPath = resolve(root, "compatibility/capabilities.json");
const scenariosPath = resolve(root, "compatibility/scenarios.json");
const generatedPath = resolve(root, "docs/roadmap/capabilities.md");
const mode = process.argv[2] ?? "--check";
const errors = [];
const expectedStatuses = ["supported", "partial", "missing", "not-applicable"];
const expectedEvidence = [
  "types",
  "conformance",
  "integration",
  "browser",
  "runtimes",
  "documentation",
  "examples",
  "security",
];

if (!new Set(["--check", "--write"]).has(mode)) {
  console.error("Usage: node scripts/validate-roadmap.mjs [--check|--write]");
  process.exit(2);
}

function loadJson(path) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    errors.push(`${relative(root, path)} is not valid JSON: ${error.message}`);
    return {};
  }
}

function expect(condition, message) {
  if (!condition) errors.push(message);
}

function exactVersion(value) {
  return typeof value === "string" && /^\d+\.\d+\.\d+$/.test(value);
}

function sha256(value) {
  return typeof value === "string" && /^[a-f0-9]{64}$/.test(value);
}

function issueUrl(value) {
  return (
    typeof value === "string" &&
    /^https:\/\/github\.com\/floodfx\/liveviewjs\/issues\/\d+$/.test(value)
  );
}

function discoverPackageManifests(directory, found = []) {
  for (const entry of readdirSync(directory)) {
    if (new Set([".git", "node_modules", "build", "dist", "coverage"]).has(entry)) {
      continue;
    }

    const path = resolve(directory, entry);
    const stats = statSync(path);
    if (stats.isDirectory()) {
      discoverPackageManifests(path, found);
    } else if (entry === "package.json") {
      found.push(path);
    }
  }
  return found;
}

function discoverFilesNamed(directory, fileName, found = []) {
  for (const entry of readdirSync(directory)) {
    if (new Set([".git", "node_modules", "build", "dist", "coverage"]).has(entry)) {
      continue;
    }

    const path = resolve(directory, entry);
    const stats = statSync(path);
    if (stats.isDirectory()) {
      discoverFilesNamed(path, fileName, found);
    } else if (entry === fileName) {
      found.push(path);
    }
  }
  return found;
}

function dependencyVersion(manifest, name) {
  for (const field of [
    "dependencies",
    "devDependencies",
    "peerDependencies",
    "optionalDependencies",
  ]) {
    if (manifest[field]?.[name]) return manifest[field][name];
  }
  return undefined;
}

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function issueReference(url) {
  const number = typeof url === "string" ? url.match(/\d+$/)?.[0] ?? "issue" : "issue";
  return `[#${number}](${url})`;
}

function renderCapabilities(manifest, compatibility) {
  const capabilities = Array.isArray(manifest.capabilities)
    ? manifest.capabilities
    : [];
  const rows = [...capabilities]
    .sort((left, right) => String(left.id ?? "").localeCompare(String(right.id ?? "")))
    .map((capability) => {
      const gaps = Array.isArray(capability.gaps) && capability.gaps.length
        ? capability.gaps.join("; ")
        : "—";
      return `| \`${escapeCell(capability.id)}\` | ${escapeCell(capability.area)} | [${escapeCell(capability.title)}](${capability.upstream}) | ${escapeCell(capability.status)} | ${issueReference(capability.ownerIssue)} | ${escapeCell(gaps)} |`;
    })
    .join("\n");

  return `<!-- Generated by scripts/validate-roadmap.mjs. Do not edit directly. -->

# LiveViewJS capability parity

Target Phoenix LiveView: **${compatibility.target?.phoenixLiveViewVersion ?? "unknown"}**

Compatibility status: **${compatibility.target?.status ?? "unknown"}**

Last reviewed: **${compatibility.lastReviewed ?? "unknown"}**

Status meanings:

- **supported:** all required evidence categories are present.
- **partial:** a working subset exists and the remaining gaps are explicit.
- **missing:** the capability is not implemented and has an owning issue.
- **not-applicable:** LiveViewJS intentionally differs and documents why.

| Capability ID | Area | Capability | Status | Owner | Known gaps |
| --- | --- | --- | --- | --- | --- |
${rows}

The machine-readable source is
[\`compatibility/capabilities.json\`](../../compatibility/capabilities.json).
Run \`npm run roadmap:write\` after changing it and
\`npm run verify:roadmap\` before submitting a pull request.
`;
}

const compatibility = loadJson(compatibilityPath);
const manifest = loadJson(capabilitiesPath);
const scenarios = loadJson(scenariosPath);
const corePackage = loadJson(resolve(root, "packages/core/package.json"));

expect(compatibility.schemaVersion === 1, "liveview.json schemaVersion must be 1");
expect(issueUrl(compatibility.trackingIssue), "liveview.json trackingIssue must be a repository issue URL");
expect(exactVersion(compatibility.target?.phoenixVersion), "target Phoenix version must be exact semver");
expect(sha256(compatibility.target?.phoenixSourceChecksum), "target Phoenix source checksum must be SHA-256");
expect(exactVersion(compatibility.target?.phoenixLiveViewVersion), "target Phoenix LiveView version must be exact semver");
expect(sha256(compatibility.target?.phoenixLiveViewSourceChecksum), "target Phoenix LiveView source checksum must be SHA-256");
expect(exactVersion(compatibility.target?.phoenixClientVersion), "target Phoenix client version must be exact semver");
expect(
  new Set(["target", "verified"]).has(compatibility.target?.status),
  "target status must be target or verified",
);
expect(
  compatibility.target?.phoenixLiveViewVersion === compatibility.target?.phoenixClientVersion,
  "target Phoenix LiveView and browser client versions must match",
);
expect(
  compatibility.release?.liveViewJsVersion === corePackage.version,
  "release.liveViewJsVersion must match packages/core/package.json",
);
expect(
  Array.isArray(compatibility.release?.verifiedPhoenixLiveViewVersions),
  "verifiedPhoenixLiveViewVersions must be an array",
);
for (const version of compatibility.release?.verifiedPhoenixLiveViewVersions ?? []) {
  expect(exactVersion(version), `verified Phoenix LiveView version must be exact semver: ${version}`);
}
expect(
  compatibility.clientPolicy?.targetVersion === compatibility.target?.phoenixClientVersion,
  "client policy target must match the pinned browser client",
);
expect(
  Array.isArray(compatibility.clientPolicy?.testedAgainstPhoenixOracle) &&
    compatibility.clientPolicy.testedAgainstPhoenixOracle.includes(compatibility.target?.phoenixClientVersion),
  "client policy must record the target as tested against the Phoenix oracle",
);
expect(
  Array.isArray(compatibility.clientPolicy?.verifiedAgainstLiveViewJs),
  "client policy verifiedAgainstLiveViewJs must be an array",
);
expect(
  Array.isArray(compatibility.clientPolicy?.testedAgainstLiveViewJs) &&
    compatibility.clientPolicy.testedAgainstLiveViewJs.includes(compatibility.target?.phoenixClientVersion),
  "client policy must record the target as tested against LiveViewJS",
);
for (const version of compatibility.clientPolicy?.verifiedAgainstLiveViewJs ?? []) {
  expect(exactVersion(version), `LiveViewJS-verified browser client version must be exact semver: ${version}`);
}
expect(
  new Set(["not-tested", "tolerated", "rejected"]).has(compatibility.clientPolicy?.olderVersions),
  "client policy must classify older versions",
);
expect(
  new Set(["tolerated", "rejected"]).has(compatibility.clientPolicy?.unlistedVersions),
  "client policy must classify unlisted versions",
);
if (compatibility.target?.status === "verified") {
  expect(
    compatibility.release.verifiedPhoenixLiveViewVersions.includes(
      compatibility.target.phoenixLiveViewVersion,
    ),
    "a verified target must appear in verifiedPhoenixLiveViewVersions",
  );
}

const oracleMixPath = resolve(root, "compatibility/phoenix/mix.exs");
const oracleMixLockPath = resolve(root, "compatibility/phoenix/mix.lock");
const oracleAssetsPath = resolve(root, "compatibility/phoenix/assets/package-lock.json");
const liveViewJsTargetPath = resolve(root, "compatibility/liveviewjs/package-lock.json");
const recorderPackagePath = resolve(root, "compatibility/recorder/package.json");
const recorderLockPath = resolve(root, "compatibility/recorder/package-lock.json");
for (const path of [oracleMixPath, oracleMixLockPath, oracleAssetsPath, liveViewJsTargetPath, recorderPackagePath, recorderLockPath]) {
  expect(existsSync(path), `compatibility input is missing: ${relative(root, path)}`);
}

function validateMorphdomLock(lock, label) {
  const liveViewClient = lock.packages?.["node_modules/phoenix_live_view"];
  const morphdomDependency = liveViewClient?.dependencies?.morphdom;
  const lockedMorphdom = lock.packages?.["node_modules/morphdom"];
  if (morphdomDependency === undefined) {
    expect(lockedMorphdom === undefined, `${label} must not retain an unreferenced morphdom package`);
    return;
  }
  expect(
    /^git\+https:\/\/github\.com\/SteffenDE\/morphdom\.git#[a-f0-9]{40}$/.test(
      lockedMorphdom?.resolved ?? "",
    ),
    `${label} morphdom dependency must use HTTPS and an immutable commit SHA`,
  );
}

if (existsSync(liveViewJsTargetPath)) {
  const targetLock = loadJson(liveViewJsTargetPath);
  const dependencies = targetLock.packages?.[""]?.dependencies ?? {};
  expect(dependencies.phoenix === compatibility.target?.phoenixVersion, "LiveViewJS target JavaScript Phoenix version must match the target");
  expect(dependencies.phoenix_live_view === compatibility.target?.phoenixClientVersion, "LiveViewJS target JavaScript LiveView version must match the target client");
  expect(
    targetLock.packages?.["node_modules/phoenix_live_view"]?.integrity?.startsWith("sha512-"),
    "LiveViewJS target JavaScript client must have locked integrity",
  );
  validateMorphdomLock(targetLock, "LiveViewJS target");
}

if (existsSync(oracleMixPath)) {
  const oracleMix = readFileSync(oracleMixPath, "utf8");
  expect(
    oracleMix.includes(`{:phoenix, "== ${compatibility.target?.phoenixVersion}"}`),
    "Phoenix oracle mix.exs must pin the declared exact Phoenix version",
  );
  expect(
    oracleMix.includes(`{:phoenix_live_view, "== ${compatibility.target?.phoenixLiveViewVersion}"}`),
    "Phoenix oracle mix.exs must pin the declared exact Phoenix LiveView version",
  );
}

if (existsSync(oracleMixLockPath)) {
  const oracleMixLock = readFileSync(oracleMixLockPath, "utf8");
  for (const [packageName, version, checksum] of [
    ["phoenix", compatibility.target?.phoenixVersion, compatibility.target?.phoenixSourceChecksum],
    ["phoenix_live_view", compatibility.target?.phoenixLiveViewVersion, compatibility.target?.phoenixLiveViewSourceChecksum],
  ]) {
    const line = oracleMixLock.split("\n").find((entry) => entry.trimStart().startsWith(`"${packageName}":`));
    expect(line?.includes(`"${version}"`), `Phoenix oracle mix.lock must resolve ${packageName} ${version}`);
    expect(line?.includes(`"hexpm", "${checksum}"`), `Phoenix oracle mix.lock checksum drift for ${packageName}`);
  }
}

if (existsSync(oracleAssetsPath)) {
  const oracleAssets = loadJson(oracleAssetsPath);
  const dependencies = oracleAssets.packages?.[""]?.dependencies ?? {};
  expect(dependencies.phoenix === compatibility.target?.phoenixVersion, "oracle JavaScript Phoenix version must match the target");
  expect(dependencies.phoenix_live_view === compatibility.target?.phoenixClientVersion, "oracle JavaScript LiveView version must match the target client");
  expect(
    oracleAssets.packages?.["node_modules/phoenix_live_view"]?.integrity?.startsWith("sha512-"),
    "oracle JavaScript LiveView client must have locked integrity",
  );
  validateMorphdomLock(oracleAssets, "oracle");
}

if (existsSync(recorderPackagePath) && existsSync(recorderLockPath)) {
  const recorderPackage = loadJson(recorderPackagePath);
  const recorderLock = loadJson(recorderLockPath);
  expect(exactVersion(recorderPackage.dependencies?.playwright), "recorder Playwright dependency must be exact semver");
  expect(
    recorderLock.packages?.["node_modules/playwright"]?.version === recorderPackage.dependencies?.playwright,
    "recorder Playwright package and lockfile must match",
  );
}

const declaredScaffoldDependencies = new Map();
for (const dependency of compatibility.implementation?.scaffoldClientDependencies ?? []) {
  expect(typeof dependency.template === "string", "each scaffold dependency needs a template path");
  expect(typeof dependency.range === "string", "each scaffold dependency needs a version range");
  expect(!declaredScaffoldDependencies.has(dependency.template), `duplicate scaffold dependency: ${dependency.template}`);
  declaredScaffoldDependencies.set(dependency.template, dependency.range);

  const path = resolve(root, dependency.template);
  if (!existsSync(path)) {
    errors.push(`declared scaffold dependency template does not exist: ${dependency.template}`);
    continue;
  }
  const match = readFileSync(path, "utf8").match(/"phoenix_live_view"\s*:\s*"([^"]+)"/);
  const actual = match?.[1];
  expect(
    actual === dependency.range,
    `${dependency.template} declares phoenix_live_view ${actual ?? "<missing>"}; baseline expects ${dependency.range}`,
  );
}

const declaredDependencies = new Map();
for (const dependency of compatibility.implementation?.clientDependencies ?? []) {
  expect(typeof dependency.manifest === "string", "each client dependency needs a manifest path");
  expect(typeof dependency.range === "string", "each client dependency needs a version range");
  expect(!declaredDependencies.has(dependency.manifest), `duplicate client dependency: ${dependency.manifest}`);
  declaredDependencies.set(dependency.manifest, dependency.range);

  const path = resolve(root, dependency.manifest);
  if (!existsSync(path)) {
    errors.push(`declared client dependency manifest does not exist: ${dependency.manifest}`);
    continue;
  }
  const packageManifest = loadJson(path);
  const actual = dependencyVersion(packageManifest, "phoenix_live_view");
  expect(
    actual === dependency.range,
    `${dependency.manifest} declares phoenix_live_view ${actual ?? "<missing>"}; baseline expects ${dependency.range}`,
  );
}

for (const path of discoverPackageManifests(root)) {
  const relativePath = relative(root, path);
  if (relativePath === "compatibility/phoenix/assets/package.json") continue;
  const packageManifest = loadJson(path);
  const actual = dependencyVersion(packageManifest, "phoenix_live_view");
  if (actual !== undefined) {
    expect(
      declaredDependencies.get(relativePath) === actual,
      `${relativePath} uses phoenix_live_view ${actual} but is not recorded accurately in liveview.json`,
    );
  }
}

for (const path of discoverFilesNamed(root, "package.json.ejs.t")) {
  const relativePath = relative(root, path);
  const match = readFileSync(path, "utf8").match(/"phoenix_live_view"\s*:\s*"([^"]+)"/);
  const actual = match?.[1];
  if (actual !== undefined) {
    expect(
      declaredScaffoldDependencies.get(relativePath) === actual,
      `${relativePath} scaffolds phoenix_live_view ${actual} but is not recorded accurately in liveview.json`,
    );
  }
}

expect(manifest.schemaVersion === 1, "capabilities.json schemaVersion must be 1");
expect(issueUrl(manifest.trackingIssue), "capabilities.json trackingIssue must be a repository issue URL");
expect(
  manifest.targetPhoenixLiveViewVersion === compatibility.target?.phoenixLiveViewVersion,
  "capability and compatibility target versions must match",
);
expect(Array.isArray(manifest.statuses), "capability statuses must be an array");
expect(Array.isArray(manifest.requiredEvidenceForSupported), "required evidence must be an array");
expect(Array.isArray(manifest.capabilities) && manifest.capabilities.length > 0, "capabilities must be a non-empty array");
expect(
  JSON.stringify([...(manifest.statuses ?? [])].sort()) === JSON.stringify([...expectedStatuses].sort()),
  `capability statuses must be exactly: ${expectedStatuses.join(", ")}`,
);
expect(
  JSON.stringify([...(manifest.requiredEvidenceForSupported ?? [])].sort()) === JSON.stringify([...expectedEvidence].sort()),
  `required evidence categories must be exactly: ${expectedEvidence.join(", ")}`,
);

const allowedStatuses = new Set(manifest.statuses ?? []);
const requiredEvidence = manifest.requiredEvidenceForSupported ?? [];
const capabilityIds = new Set();

for (const capability of manifest.capabilities ?? []) {
  const prefix = capability.id ? `capability ${capability.id}` : "capability <missing-id>";
  expect(typeof capability.id === "string" && /^[a-z0-9]+(?:[.-][a-z0-9]+)*$/.test(capability.id), `${prefix} has an invalid id`);
  expect(!capabilityIds.has(capability.id), `${prefix} has a duplicate id`);
  capabilityIds.add(capability.id);
  expect(typeof capability.area === "string" && capability.area.length > 0, `${prefix} needs an area`);
  expect(typeof capability.title === "string" && capability.title.length > 0, `${prefix} needs a title`);
  expect(allowedStatuses.has(capability.status), `${prefix} has unknown status ${capability.status}`);
  expect(typeof capability.upstream === "string" && capability.upstream.startsWith("https://"), `${prefix} needs an upstream reference`);
  expect(issueUrl(capability.ownerIssue), `${prefix} needs a LiveViewJS owner issue`);
  expect(typeof capability.summary === "string" && capability.summary.length > 0, `${prefix} needs a summary`);
  expect(Array.isArray(capability.gaps), `${prefix} gaps must be an array`);
  expect(capability.evidence && typeof capability.evidence === "object" && !Array.isArray(capability.evidence), `${prefix} evidence must be an object`);

  if (new Set(["partial", "missing"]).has(capability.status)) {
    expect((capability.gaps?.length ?? 0) > 0, `${prefix} must describe its gaps`);
  }
  if (capability.status === "not-applicable") {
    expect((capability.gaps?.length ?? 0) > 0, `${prefix} must document the intentional difference`);
  }
  if (capability.status === "supported") {
    expect((capability.gaps?.length ?? 0) === 0, `${prefix} cannot be supported while gaps remain`);
    for (const category of requiredEvidence) {
      const items = capability.evidence?.[category];
      expect(Array.isArray(items) && items.length > 0, `${prefix} is supported but lacks ${category} evidence`);
    }
  }

  for (const [category, items] of Object.entries(capability.evidence ?? {})) {
    expect(requiredEvidence.includes(category), `${prefix} has unknown evidence category ${category}`);
    expect(Array.isArray(items), `${prefix} evidence.${category} must be an array`);
    for (const item of Array.isArray(items) ? items : []) {
      expect(typeof item === "string" && item.length > 0, `${prefix} evidence.${category} contains an invalid id`);
      if (typeof item !== "string" || item.length === 0) continue;
      const [file, marker, ...extra] = item.split("#");
      expect(extra.length === 0, `${prefix} evidence.${category} contains more than one # separator: ${item}`);
      expect(!file.startsWith("/") && !file.split("/").includes(".."), `${prefix} evidence.${category} must be repository-relative: ${item}`);
      const evidencePath = resolve(root, file);
      expect(existsSync(evidencePath), `${prefix} evidence.${category} file does not exist: ${file}`);
      if (existsSync(evidencePath) && marker) {
        expect(
          readFileSync(evidencePath, "utf8").includes(marker),
          `${prefix} evidence.${category} marker was not found: ${item}`,
        );
      }
    }
  }
}

expect(scenarios.schemaVersion === 1, "scenarios.json schemaVersion must be 1");
expect(Number.isInteger(scenarios.seed), "scenarios.json seed must be an integer");
expect(Array.isArray(scenarios.scenarios) && scenarios.scenarios.length > 0, "scenarios.json must contain scenarios");
const scenarioIds = new Set();
for (const scenario of scenarios.scenarios ?? []) {
  const prefix = scenario.id ? `scenario ${scenario.id}` : "scenario <missing-id>";
  expect(typeof scenario.id === "string" && /^[a-z0-9]+(?:[.-][a-z0-9]+)*$/.test(scenario.id), `${prefix} has an invalid id`);
  expect(!scenarioIds.has(scenario.id), `${prefix} has a duplicate id`);
  scenarioIds.add(scenario.id);
  expect(capabilityIds.has(scenario.capabilityId), `${prefix} references an unknown capability`);
  expect(typeof scenario.path === "string" && scenario.path.startsWith("/"), `${prefix} needs an absolute route path`);
  expect(Array.isArray(scenario.actions), `${prefix} actions must be an array`);
  for (const action of scenario.actions ?? []) {
    expect(action.type === "click", `${prefix} has unsupported action type ${action.type}`);
    expect(typeof action.selector === "string" && action.selector.length > 0, `${prefix} action needs a selector`);
    expect(typeof action.checkpoint === "string" && action.checkpoint.length > 0, `${prefix} action needs a checkpoint`);
  }
}

const generated = renderCapabilities(manifest, compatibility);
if (mode === "--write" && errors.length === 0) {
  mkdirSync(dirname(generatedPath), { recursive: true });
  writeFileSync(generatedPath, generated);
}

if (mode === "--check") {
  if (!existsSync(generatedPath)) {
    errors.push("docs/roadmap/capabilities.md is missing; run npm run roadmap:write");
  } else if (readFileSync(generatedPath, "utf8") !== generated) {
    errors.push("docs/roadmap/capabilities.md is stale; run npm run roadmap:write");
  }
}

if (errors.length > 0) {
  console.error("Roadmap contract validation failed:\n");
  for (const error of errors) console.error(`- ${error}`);
  process.exit(1);
}

console.log(
  mode === "--write"
    ? `Wrote ${relative(root, generatedPath)} and validated the roadmap contract.`
    : `Roadmap contract is valid (${manifest.capabilities.length} capabilities, Phoenix LiveView ${compatibility.target.phoenixLiveViewVersion} target).`,
);
